
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 18 2025 13:38:19 IST (Oct 18 2025 08:08:19 UTC)

// Verification Directory fv/kogge_stone_adder 

module kogge_stone_adder(operand_a_i, operand_b_i, result_o,
     overflow_o);
  input [7:0] operand_a_i, operand_b_i;
  output [7:0] result_o;
  output overflow_o;
  wire [7:0] operand_a_i, operand_b_i;
  wire [7:0] result_o;
  wire overflow_o;
  wire n_0, n_1, n_3, n_4, n_5, n_7, n_8, n_9;
  wire n_11, n_12, n_13, n_15, n_16, n_17, n_19, n_20;
  wire n_21, n_23, n_24, n_25, n_27, n_28, n_29;
  OAI2BB1X4 g528__2398(.A0N (operand_b_i[7]), .A1N (operand_a_i[7]),
       .B0 (n_29), .Y (overflow_o));
  MX2X4 g529__5107(.S0 (n_28), .B (n_3), .A (n_27), .Y (result_o[7]));
  OR2X1 g530__6260(.A (n_28), .B (n_27), .Y (n_29));
  MX2X4 g532__4319(.S0 (n_24), .B (n_23), .A (n_25), .Y (result_o[6]));
  AOI22XL g531__8428(.A0 (n_25), .A1 (n_24), .B0 (operand_b_i[6]), .B1
       (operand_a_i[6]), .Y (n_28));
  INVXL g533(.A (n_23), .Y (n_25));
  MX2X4 g535__5526(.S0 (n_20), .B (n_19), .A (n_21), .Y (result_o[5]));
  AOI22XL g534__6783(.A0 (n_21), .A1 (n_20), .B0 (operand_b_i[5]), .B1
       (operand_a_i[5]), .Y (n_23));
  INVXL g536(.A (n_19), .Y (n_21));
  MX2X4 g538__3680(.S0 (n_16), .B (n_15), .A (n_17), .Y (result_o[4]));
  AOI22XL g537__1617(.A0 (n_17), .A1 (n_16), .B0 (operand_b_i[4]), .B1
       (operand_a_i[4]), .Y (n_19));
  INVXL g539(.A (n_15), .Y (n_17));
  AOI22XL g540__2802(.A0 (n_12), .A1 (n_13), .B0 (operand_b_i[3]), .B1
       (operand_a_i[3]), .Y (n_15));
  MX2X4 g541__1705(.S0 (n_13), .B (n_11), .A (n_12), .Y (result_o[3]));
  INVXL g542(.A (n_11), .Y (n_12));
  MX2X4 g544__5122(.S0 (n_8), .B (n_7), .A (n_9), .Y (result_o[2]));
  AOI22XL g543__8246(.A0 (n_9), .A1 (n_8), .B0 (operand_b_i[2]), .B1
       (operand_a_i[2]), .Y (n_11));
  INVXL g545(.A (n_7), .Y (n_9));
  MX2X4 g547__7098(.S0 (n_5), .B (n_1), .A (n_4), .Y (result_o[1]));
  AOI22XL g546__6131(.A0 (n_5), .A1 (n_4), .B0 (operand_b_i[1]), .B1
       (operand_a_i[1]), .Y (n_7));
  INVXL g549(.A (n_3), .Y (n_27));
  AND2X4 g550__1881(.A (n_1), .B (n_0), .Y (result_o[0]));
  XOR2XL g554__5115(.A (operand_b_i[1]), .B (operand_a_i[1]), .Y (n_5));
  XOR2XL g553__7482(.A (operand_b_i[3]), .B (operand_a_i[3]), .Y
       (n_13));
  XOR2XL g551__4733(.A (operand_b_i[5]), .B (operand_a_i[5]), .Y
       (n_20));
  XOR2XL g555__6161(.A (operand_b_i[6]), .B (operand_a_i[6]), .Y
       (n_24));
  XOR2XL g557__9315(.A (operand_b_i[4]), .B (operand_a_i[4]), .Y
       (n_16));
  XOR2XL g552__9945(.A (operand_b_i[2]), .B (operand_a_i[2]), .Y (n_8));
  XOR2XL g556__2883(.A (operand_b_i[7]), .B (operand_a_i[7]), .Y (n_3));
  INVXL g548(.A (n_1), .Y (n_4));
  NAND2XL g559__2346(.A (operand_b_i[0]), .B (operand_a_i[0]), .Y
       (n_1));
  OR2X1 g558__1666(.A (operand_a_i[0]), .B (operand_b_i[0]), .Y (n_0));
endmodule

