
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 18 2025 11:20:52 IST (Oct 18 2025 05:50:52 UTC)

// Verification Directory fv/kogge_stone_adder 

module kogge_stone_adder(operand_a_i, operand_b_i, result_o,
     overflow_o);
  input [7:0] operand_a_i, operand_b_i;
  output [7:0] result_o;
  output overflow_o;
  wire [7:0] operand_a_i, operand_b_i;
  wire [7:0] result_o;
  wire overflow_o;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_10;
  wire n_11, n_13, n_14, n_15, n_17, n_18, n_19, n_21;
  wire n_22, n_23, n_25, n_26, n_27;
  MX2X1 g622__2398(.A (n_26), .B (n_25), .S0 (n_27), .Y (result_o[7]));
  AO22X1 g621__5107(.A0 (n_27), .A1 (n_26), .B0 (operand_b_i[7]), .B1
       (operand_a_i[7]), .Y (overflow_o));
  CLKINVX1 g623(.A (n_25), .Y (n_26));
  AOI22X1 g624__6260(.A0 (n_22), .A1 (n_23), .B0 (operand_b_i[6]), .B1
       (operand_a_i[6]), .Y (n_25));
  MX2X1 g625__4319(.A (n_23), .B (n_21), .S0 (n_22), .Y (result_o[6]));
  CLKINVX1 g626(.A (n_21), .Y (n_23));
  MX2X1 g628__8428(.A (n_18), .B (n_17), .S0 (n_19), .Y (result_o[5]));
  AOI22X1 g627__5526(.A0 (n_19), .A1 (n_18), .B0 (operand_b_i[5]), .B1
       (operand_a_i[5]), .Y (n_21));
  CLKINVX1 g629(.A (n_17), .Y (n_18));
  MX2X1 g631__6783(.A (n_14), .B (n_13), .S0 (n_15), .Y (result_o[4]));
  AOI22X1 g630__3680(.A0 (n_15), .A1 (n_14), .B0 (operand_b_i[4]), .B1
       (operand_a_i[4]), .Y (n_17));
  CLKINVX1 g632(.A (n_13), .Y (n_14));
  AOI22X1 g633__1617(.A0 (n_11), .A1 (n_10), .B0 (operand_b_i[3]), .B1
       (operand_a_i[3]), .Y (n_13));
  CLKXOR2X1 g634__2802(.A (n_11), .B (n_10), .Y (result_o[3]));
  MX2X1 g636__1705(.A (n_8), .B (n_1), .S0 (n_7), .Y (result_o[2]));
  OAI21X1 g635__5122(.A0 (n_8), .A1 (n_7), .B0 (n_0), .Y (n_10));
  MX2X1 g638__8246(.A (n_5), .B (n_2), .S0 (n_4), .Y (result_o[1]));
  AOI22X1 g637__7098(.A0 (n_5), .A1 (n_4), .B0 (operand_b_i[1]), .B1
       (operand_a_i[1]), .Y (n_7));
  OA21X1 g641__6131(.A0 (operand_a_i[0]), .A1 (operand_b_i[0]), .B0
       (n_2), .Y (result_o[0]));
  CLKINVX1 g640(.A (n_1), .Y (n_8));
  CLKXOR2X1 g644__1881(.A (operand_b_i[3]), .B (operand_a_i[3]), .Y
       (n_11));
  CLKXOR2X1 g645__5115(.A (operand_b_i[1]), .B (operand_a_i[1]), .Y
       (n_4));
  CLKXOR2X1 g643__7482(.A (operand_b_i[2]), .B (operand_a_i[2]), .Y
       (n_1));
  CLKXOR2X1 g646__4733(.A (operand_b_i[6]), .B (operand_a_i[6]), .Y
       (n_22));
  CLKINVX1 g639(.A (n_2), .Y (n_5));
  CLKXOR2X1 g648__6161(.A (operand_b_i[4]), .B (operand_a_i[4]), .Y
       (n_15));
  CLKXOR2X1 g647__9315(.A (operand_b_i[7]), .B (operand_a_i[7]), .Y
       (n_27));
  CLKXOR2X1 g642__9945(.A (operand_b_i[5]), .B (operand_a_i[5]), .Y
       (n_19));
  NAND2XL g650__2883(.A (operand_b_i[2]), .B (operand_a_i[2]), .Y
       (n_0));
  NAND2XL g649__2346(.A (operand_b_i[0]), .B (operand_a_i[0]), .Y
       (n_2));
endmodule

